# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 490e1e497832d2bcac10a5b64d616982df6a3528865e679d2934666a45b97d82d7daa5cd592f581ea08f0e1717d69968caddd0c33ef5628beda7a67fab2c9c40

test:
  secret_key_base: 7e62fafcbeb6f1276d6c74df59ecd0163a6ee2fca7e40ad0cbbd8ec5a217db58fb68760c9f56d764baa8ac2d177f9285173c17fa27b1cab6b05b05a49d12b628

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
